name: Oxmart Lint and Tests
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  linter:
    name: Update node version
    runs-on: ubuntu-latest
    steps:
      - name: Create node-version
        run: |
          curl https://nodejs.org/en/download \|
          grep -oE 'Latest LTS Version<!-- -->: <strong>[0-9]+\.[0-9]+\.[0-9]+</strong>' \|
          grep -oE '[0-9]+\.[0-9]+\.[0-9]+' > .node-version

      - uses: EndBug/add-and-commit@v7
        with:
          add: '.node-version'
          author_name: Aadesh Shrestha
          message: 'update node version'