name: Oxmart Lint and Tests
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  linter:
    name: Update node version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            token: ${{ secrets.FPAT }}
      - name: Create node-version
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          
      - name: Echo node version
        run: cat .node-version

      - uses: EndBug/add-and-commit@v9
        with:
          add: '.node-version'
          author_name: Aadesh Shrestha
          message: 'update node version'